package com.litwago.converters;

import com.litwago.dto.*;
import org.springframework.stereotype.Component;

import java.util.stream.Collectors;

@Component
public class CouplingDtoOutConverter implements Converter<com.litwago.models.Coupling, Coupling> {

    @Override
    public Coupling convert(com.litwago.models.Coupling c) {
        return Coupling.builder()
            .id(c.getId())
            .oldTruckNumber(c.getOldTruckNumber())
            .newTruckNumber(c.getNewTruckNumber())
            .trailerNumber(c.getTrailerNumber())
            .location(Location.builder()
                .countryCode(c.getCountryCode())
                .postalCode(c.getPostalCode())
                .build())
            .date(c.getDate())
            .hasSeal(c.isHasSeal())
            .trailerChange(c.getTrailerChange() == null ? null : TrailerChange.builder()
                .fuelRefrigerator(c.getTrailerChange().getFuelRefrigerator() == null ? null : FuelRefrigerator.builder()
                    .liters(c.getTrailerChange().getFuelRefrigerator().getLiters())
                    .motoHours(c.getTrailerChange().getFuelRefrigerator().getMotoHours())
                    .signalizationWorks(c.getTrailerChange().getFuelRefrigerator().isSignalizationWorks())
                    .build())
                .equipment(Equipment.builder()
                    .belts(c.getTrailerChange().getEquipment().getBelts())
                    .cargoShelves(c.getTrailerChange().getEquipment().getCargoShelves())
                    .spareWheels(c.getTrailerChange().getEquipment().getSpareWheels())
                    .chocks(c.getTrailerChange().getEquipment().getChocks())
                    .mountingBrackets(c.getTrailerChange().getEquipment().getMountingBrackets())
                    .hooks(c.getTrailerChange().getEquipment().getHooks())
                    .rods(c.getTrailerChange().getEquipment().getRods())
                    .palettes(c.getTrailerChange().getEquipment().getPalettes())
                    .crossbar2Tier(c.getTrailerChange().getEquipment().getCrossbar2Tier())
                    .ladders(c.getTrailerChange().getEquipment().getLadders())
                    .fasteningBoards(c.getTrailerChange().getEquipment().getFasteningBoards())
                    .rubberMatsSmall(c.getTrailerChange().getEquipment().getRubberMatsSmall())
                    .rubberMatsLarge(c.getTrailerChange().getEquipment().getRubberMatsLarge())
                    .build())
                .documents(Documents.builder()
                    .vehicleRegistration(c.getTrailerChange().getDocuments().getVehicleRegistration())
                    .vehicleInspection(c.getTrailerChange().getDocuments().getVehicleInspection())
                    .conformity(c.getTrailerChange().getDocuments().getConformity())
                    .insurancePolicy(c.getTrailerChange().getDocuments().getInsurancePolicy())
                    .atpFrc(c.getTrailerChange().getDocuments().getAtpFrc())
                    .euro(c.getTrailerChange().getDocuments().getEuro())
                    .thermographPrinter(c.getTrailerChange().getDocuments().getThermographPrinter())
                    .thermograph(c.getTrailerChange().getDocuments().getThermograph())
                    .alarmPanel(c.getTrailerChange().getDocuments().getAlarmPanel())
                    .keyNumber(c.getTrailerChange().getDocuments().getKeyNumber())
                    .build())
                .tireDamages(TireDamages.builder()
                    .firstAxis(TireAxis.builder()
                        .left(TireDamage.builder()
                            .damage(c.getTrailerChange().getTireDamages().getFirstLeftDamage())
                            .manufacturer(c.getTrailerChange().getTireDamages().getFirstLeftManufacturer())
                            .build())
                        .right(TireDamage.builder()
                            .damage(c.getTrailerChange().getTireDamages().getFirstRightDamage())
                            .manufacturer(c.getTrailerChange().getTireDamages().getFirstRightManufacturer())
                            .build())
                        .build())
                    .secondAxis(TireAxis.builder()
                        .left(TireDamage.builder()
                            .damage(c.getTrailerChange().getTireDamages().getSecondLeftDamage())
                            .manufacturer(c.getTrailerChange().getTireDamages().getSecondLeftManufacturer())
                            .build())
                        .right(TireDamage.builder()
                            .damage(c.getTrailerChange().getTireDamages().getSecondRightDamage())
                            .manufacturer(c.getTrailerChange().getTireDamages().getSecondRightManufacturer())
                            .build())
                        .build())
                    .thirdAxis(TireAxis.builder()
                        .left(TireDamage.builder()
                            .damage(c.getTrailerChange().getTireDamages().getThirdLeftDamage())
                            .manufacturer(c.getTrailerChange().getTireDamages().getThirdLeftManufacturer())
                            .build())
                        .right(TireDamage.builder()
                            .damage(c.getTrailerChange().getTireDamages().getThirdRightDamage())
                            .manufacturer(c.getTrailerChange().getTireDamages().getThirdRightManufacturer())
                            .build())
                        .build())
                    .build())
                .truckDamages(TruckDamages.builder()
                    .damages(c.getTrailerChange().getTruckDamages().getDamages().stream()
                        .map(d -> TruckDamage.builder()
                            .damage(d.getDamage())
                            .area(d.getArea())
                            .build())
                        .collect(Collectors.toList()))
                    .otherDamage(c.getTrailerChange().getTruckDamages().getOtherDamage())
                    .build())
                .build())
                .oldDriver(c.getOldDriver() == null ? null : Driver.builder()
                    .id(c.getOldDriver().getId())
//                    .signature(c.getOldDriverSignature())
                    .build())
                .newDriver(c.getNewDriver() == null ? null : Driver.builder()
                    .id(c.getNewDriver().getId())
//                    .signature(c.getNewDriverSignature())
                    .build())
            .build();
    }
}
